version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    environment:
      MONGODB_URL: 'mongodb://mongo:27017/Cluster0'

  mongo:
    image: mongo
    ports:
      - '27017:27017'
